version: '3'

services: 
    app:
        container_name: setup-nodejs
        build:
            context: .
            dockerfile: dockerfile
        volumes: 
            - ./:/usr/src/app
        environment: 
            - PORT=3000
            - MONGO_URI=mongodb://mongo:27017
        ports: 
            - 3000:3000
        depends_on:
          - mongo
    mongo:
        container_name: mongodb
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=12345
volumes:
 mongodb: