name: Deploy

on: 
    workflow_dispatch:
    push:
        branches: [main, development]

jobs:
    test-ci:
        runs-on: ubuntu-20.04

        strategy:
            matrix: 
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with: 
                node-version: ${{matrix.node-version}}
            - run: npm ci
            - run: npm run test

    deploy-test:
        needs: test-ci
        if: github.ref == 'refs/heads/develop'
        runs-on : ubuntu 20.04
        concurrency: deploy-to-test
        enviroment: test
        steps:
            - uses: actions/checkout@v2
            - name: Use Nodejs 10.x
              uses: actions/setup-node@v2
              with:
                node-version: 16.x
            - run: docker build -t setup-Nodejs
            - run: echo "Deploy"

    deploy-production:
        needs: test-ci
        if: github.ref == 'refs/heads/main'
        runs-on : ubuntu 20.04
        concurrency: deploy-to-production
        enviroment: production
        steps:
            - uses: actions/checkout@v2
            - name: Use Nodejs 10.x
              uses: actions/setup-node@v2
              with:
                node-version: 16.x
            - run: docker build -t setup-Nodejs
            - run: echo "Deploy"
